version: "3.4"
networks:
  constr-sw-2022-2:
    external: true
volumes:
  keycloak-data:
    external: true
  mongodb-data:
    external: true
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  # keycloak-api:
    # container_name: keycloak-api
    # ...
    # depends_on:
    #   - keycloak
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a12345678
    volumes:
      - mongodb-data:/data/mongodb
    networks:
      - constr-sw-2022-2
  classrooms:
    container_name: classrooms
    build: ./classrooms
    ports:
      - 8085:8085
    environment:
      - KEYCLOAK_API_HOST=host.docker.internal
      - KEYCLOAK_API_PORT=3000
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=a12345678
      - API_PORT=8085
    networks:
      - constr-sw-2022-2
    depends_on:
      #- keycloak-api
      - mongodb
